version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs"
  ]
  skip_doc_coverage = [
    "arrow-function-expression",
    "class-expression",
    "function-declaration",
    "method-definition"
  ]
