pull_request_rules:
  - name: Automatic merge for depfu pull requests
    conditions:
      - author=depfu[bot]
      - base=main
      - status-success=continuous-integration
    actions:
      merge:
        method: merge