allowBuilds:
  esbuild: false
  lefthook: true
minimumReleaseAgeExclude:
  - lefthook-darwin-arm64@2.1.16
  - lefthook-darwin-x64@2.1.16
  - lefthook-freebsd-arm64@2.1.16
  - lefthook-freebsd-x64@2.1.16
  - lefthook-linux-arm64@2.1.16
  - lefthook-linux-x64@2.1.16
  - lefthook-openbsd-arm64@2.1.16
  - lefthook-openbsd-x64@2.1.16
  - lefthook-windows-arm64@2.1.16
  - lefthook-windows-x64@2.1.16
  - lefthook@2.1.16
overrides:
  esbuild@>=0.17.0 <0.28.1: ^0.28.2
  ip-address@<=10.1.0: ^10.1.1
  nanoid@<3.3.18: 3.3.18
  postcss@<8.5.23: 8.5.23
