ignoredBuiltDependencies:
  - esbuild
onlyBuiltDependencies:
  - node-libcurl
overrides:
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3'
  flatted@<=3.4.1: '>=3.4.2'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  tar@<=7.5.10: '>=7.5.11'
  vite@>=7.0.0 <=7.3.2: '>=7.3.2'
